### ISSUE TITLE
openwechatsdk 不能正常install

### ISSUE THREAD

**Issue by chesongsong** [JarvanMo/OpenWeChatSDK#1]
[!] Error installing OpenWeChatSDK
[!] /usr/bin/git clone https://github.com/JarvanMo/OpenWeChatSDK.git /var/folders/k6/n69hgzl15nqg5qsp4kgwrfq80000gn/T/d20220812-27805-11eqbk4 --template= --single-branch --depth 1 --branch 1.9.2+1

Cloning into '/var/folders/k6/n69hgzl15nqg5qsp4kgwrfq80000gn/T/d20220812-27805-11eqbk4'...
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Operation timed out

**Comment by JarvanMo** [comment]
这个不是我的问题吧，你连不上github了
